kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    architectures:
    - amd64
    channels:
    - name: stable-4.19
      type: ocp
      minVersion: 4.19.21
      maxVersion: 4.19.21
    graph: true