#!/bin/bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
declare _HOME=$(cd -P $(dirname $0) && pwd)

REGISTRY=artifactorye.home.local:443
REGISTRY_NS=gitops

OCMIRROR=oc-mirror
OCMIRROR_FLAGS="--v2"
DATA_DIR="${_HOME}/data"

_ENVS="lab|dev|qa|prd"
_TYPES="operator|release"

_VERSION=$1 # 4.x
_SENV=$2
_TYPE=$3

[[ "${_VERSION}" = "" || "${_SENV}" = "" || "${_TYPE}" = "" ]] && \
echo "Usage: $0 4.x Environnement Type" && \
echo "Environnement: ${_ENVS}" && \
echo "Type: ${_TYPES}" && \
echo -en "Exemples:\n $0 4.19 dev release\n $0 4.19 dev operator\n" && exit 1

echo $_SENV|grep -Eqw ${_ENVS}
[[ $? -ne 0 ]] && echo "\"${_SENV}\" est un environement invalide. Choisir entre ${_ENVS}" && exit 1

echo $_TYPE|grep -Eqw ${_TYPES}
[[ $? -ne 0 ]] && echo "\"${_TYPE}\" est un environement invalide. Choisir entre ${_TYPES}" && exit 1

OCMIRROR_WORKSPACE=${_HOME}/${_VERSION}/${_SENV}
IMAGESET="${_HOME}/${_VERSION}/${_TYPE}.yaml"

[[ ! -f ${IMAGESET} ]] && echo "Imposible d'acceder a ${IMAGESET}" && exit 1
[[ "${REGISTRY}" = "" ]] && echo "Definir REGISTRY" && exit 1
[[ "${REGISTRY_NS}" = "" ]] && echo "Definir REGISTRY_NS" && exit 1

TS=$(date "+%Y%m%d%H%M%S")
GIT_WORKSPACE=${_HOME}/${_VERSION}/${_SENV}/${TS}
FROM=${OCMIRROR_WORKSPACE}/mirror_seq${SEQUENCE}_000000.tar
# oc-mirror v2 = 4.19+
FROMDIR=${OCMIRROR_WORKSPACE}/
FROM=${OCMIRROR_WORKSPACE}/mirror_000001.tar

if [[ ! -f ${FROM} ]]; then
  echo -en "Il n'existe pas de sync ayant produit ${FROM}\n"
  ls ${OCMIRROR_WORKSPACE}/
  exit 1
else
  echo FROM = ${FROM}
fi

echo "$OCMIRROR --from file://${FROMDIR} --config=${IMAGESET} $OCMIRROR_FLAGS docker://${REGISTRY}/${REGISTRY_NS}/${_SENV}"
$OCMIRROR --from file://${FROMDIR} --config=${IMAGESET} $OCMIRROR_FLAGS docker://${REGISTRY}/${REGISTRY_NS}/${_SENV}

mkdir -p ${GIT_WORKSPACE}
echo "Copie dans un autre repertoire car le contenu du workspace ie working-dir est ecrase au prochain sync de ${_VERSION}"
cp -r ${OCMIRROR_WORKSPACE}/working-dir/cluster-resources \
      ${OCMIRROR_WORKSPACE}/working-dir/signatures \
      ${GIT_WORKSPACE}

SIGNATURES_FILE=${OCMIRROR_WORKSPACE}/working-dir/cluster-resources/signature-configmap.yaml
if [[ -f ${SIGNATURES_FILE} ]]; then
  echo "Patch configmap mirrored-release-signatures: ${SIGNATURES_FILE}"
  echo "Copier le resultat dans osus/templates ou determiner comment 4.19+ le consomme"
fi
echo "Stager le repertoire suivant dans GIT: ${_VERSION}/${_SENV}/${TS} pour verif history futur"